manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: hackpadplusplus-config
      url-base: https://github.com/0x62b
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: hackpadplusplus-config
      remote: hackpadplusplus-config
      revision: main
  self:
    path: config